### ISSUE TITLE
请问，支持textview的两端对齐格式吗？

### ISSUE THREAD

**Issue by merhong2012** [hongyangAndroid/MixtureTextView#2]
请问，支持textview的两端对齐格式吗？

**Comment by hongyangAndroid** [comment]
这个控件是针对大量文本，不是单行文本，（两端）分散对齐有什么应用场景？

**Comment by merhong2012** [comment]
比如类似网易新闻的新闻详情页面

**Comment by hongyangAndroid** [comment]
来个截图？

**Comment by merhong2012** [comment]
类似这样.......................
![screenshot_2015-08-22-15-45-17](https://cloud.githubusercontent.com/assets/7665010/9423044/09586ba0-48e5-11e5-8c51-045dff7e23fc.png)

**Comment by hongyangAndroid** [comment]
好吧，这应该不叫分散（两端）对齐~~ 这样的分段式的会支持。
